// The edge worlds, from the ground: Mustafar, Scarif and Bespin's Cloud
// City. (sites/index.js has what a site is.)

export const SITES = {
  mustafar: {
    place: 'The lava fields of Mustafar',
    line: 'Black rock, rivers of fire, and ash falling like snow.',
    sky: {
      zenith: '#160c0b',
      horizon: '#b4441c',
      below: '#3a1408',
      haze: 0.95,
      hazeColor: '#ff6a2a',
      suns: [{ az: 2.4, el: 0.3, color: '#ffb27a', size: 0.022, glow: 1.6 }],
      clouds: { cover: 0.62, color: '#5a2a1e', shade: '#1e100c', scale: 0.7, speed: 0.006, sharp: 0.8 },
      stars: 0,
    },
    fog: { color: '#5e2414', density: 0.0012 },
    light: { sun: 2.4, sky: '#9a5640', ground: '#6a240c', ambient: 0.85 },
    dust: '#2a2220',
    edge: 'Nothing out there but more lava. Better turn back before your boots melt.',
    ground: { detail: 'ash', detailLook: { color: 0.8, normal: 0.8 },
      seed: 31,
      wind: 0.8,
      layers: [
        { type: 'swell', scale: 320, height: 7 },
        { type: 'ridges', scale: 150, height: 10 },
        { type: 'channels', scale: 360, depth: 11, width: 0.08 },
        { type: 'ridges', scale: 38, height: 2.2 },
        { type: 'mountains', from: 650, to: 2600, height: 420, scale: 1100 },
        // the bank Obi-Wan stood on, and the black butte the lava falls pour off
        { type: 'island', at: [300, 380], r: 60, height: 7 },
        { type: 'island', at: [-390, 80], r: 75, height: 32, core: 0.78, ragged: 0.12 },
      ],
      palette: {
        low: '#3a322e',
        high: '#564a43',
        rock: '#191515',
        accent: '#5a3424',
        deep: '#221c1a',
        hLow: -6,
        hHigh: 14,
        rockAt: 0.34,
        accentCover: 0.18,
        grain: 0.8,
        roughness: 0.9,
        wet: { level: 2.5, band: 3, color: '#8a2208' },
        mark: '#120e0d',
      },
    },
    // (video: the game's lava film flows in the rivers on high and ultra, lavaFilm.js)
    water: { level: 2.5, color: '#ff3c06', deep: '#240703', kind: 'lava', glow: 2.1, video: 'volcano' },
    weather: [
      { kind: 'ash', count: 2600, color: '#3a3030' },
      { kind: 'embers', count: 900 },
    ],
    land: { at: [90, 0], yaw: 1.07 },
    lines: {
      out: {
        xwing: [['luke', 'Mustafar. This is where it happened, Artoo. Where my father…'], ['r2', '(A low, mournful whistle.)']],
        falcon: [['han', 'Whoa. Don’t touch anything, Chewie. Don’t breathe anything either.'], ['chewie', '(A worried growl, fur smoking.)']],
        cruiser: [['morty', 'Rick, the ground’s on fire! The whole planet’s on fire!'], ['rick', 'It’s a volcano planet, Morty. The Sith love a theme.']],
        rv: [['jesse', 'Yo, it’s like a thousand degrees out here, Mr. White.'], ['walt', 'One thousand two hundred, at the lava’s surface. Keep your feet on the rock.']],
      },
    },
    places: [
      {
        id: 'platform',
        name: 'The landing platform',
        at: [-70, 150],
        r: 30,
        flat: { r: 28 },
        about: 'Where Padmé’s skiff set down at the edge of the facility, and where Anakin, sure she had betrayed him, choked her in front of Obi-Wan.',
        lines: {
          xwing: [['luke', 'My mother came here, didn’t she, Artoo? To bring him back.'], ['r2', '(A very quiet beep.)']],
          falcon: [['han', 'Nice ship. Royal yacht, chrome all over. Somebody important came here.']],
          cruiser: [['morty', 'Th-that’s the shiny ship from the prequels, Rick!'], ['rick', 'Chrome, Morty. On a lava planet. Real smart.']],
        },
        things: [
          { kind: 'mpad', at: [0, 0], yaw: 0.3 },
          { kind: 'crates', at: [14, -10] },
          { kind: 'crates', at: [-15, 8] },
          { kind: 'lamp', at: [17, 6], opts: { h: 5, light: '#ffb070', color: '#2a2828' } },
          { kind: 'lamp', at: [-16, -7], opts: { h: 5, light: '#ffb070', color: '#2a2828' } },
        ],
      },
      {
        id: 'facility',
        name: 'The mining facility',
        at: [-200, 300],
        r: 60,
        flat: { r: 42, h: 5 },
        about: 'Klegger Corp’s lava-collection plant, where the Separatist council hid at the end of the war, and where Anakin, now Vader, came to end them.',
        lines: {
          xwing: [['luke', 'The Separatists hid here. He came alone, and none of them left.']],
          falcon: [['han', 'Mining outfit. Big one. Bet the pay’s lousy and the heat’s worse.'], ['chewie', '(A grunt of agreement.)']],
          rv: [['walt', 'They’re harvesting minerals out of the lava itself. That’s… actually rather elegant.'], ['jesse', 'Elegant? It’s a murder castle, yo.']],
        },
        things: [
          { kind: 'mining', at: [0, 0], yaw: 0 },
          { kind: 'smoke', at: [10, -12], abs: true, y: 58, solid: false, opts: { h: 70, n: 8, color: '#3a302c' } },
          { kind: 'lamp', at: [-26, 24], opts: { h: 6, light: '#ffb070', color: '#2a2828' } },
          { kind: 'lamp', at: [12, 27], opts: { h: 6, light: '#ffb070', color: '#2a2828' } },
          { kind: 'crates', at: [-16, 27] },
          { kind: 'crates', at: [-30, 12] },
        ],
        // (the lava it reaches back over)
        pits: [{ at: [0, -62], r: 34, depth: 16 }],
      },
      {
        id: 'river',
        name: 'The lava river',
        at: [175, 25],
        r: 60,
        about: 'Where the duel went down the river: Obi-Wan and Anakin on a collector arm adrift on the lava, then leaping to the droid platforms, still fighting.',
        lines: {
          xwing: [['luke', 'They fought all the way down this river. Master and apprentice.'], ['r2', '(A nervous trill.)']],
          falcon: [['han', 'Who sword-fights on a lava river? Who does that?']],
          cruiser: [['rick', 'Laser swords on a raft on a lava river, Morty. Peak space-wizard decision making.'], ['morty', 'It’s actually kind of awesome, Rick.']],
        },
        pits: [{ at: [0, 0], r: 72, depth: 14, cone: true }],
      },
      {
        id: 'highground',
        name: 'The high ground',
        at: [300, 360],
        r: 32,
        about: 'A bank of black sand above the river. “It’s over, Anakin. I have the high ground.” He jumped anyway.',
        lines: {
          xwing: [['luke', 'Ben stood here. He left my father on that bank, burning.'], ['r2', '(A long, sad whistle.)']],
          falcon: [['han', 'High ground, huh. Kid, always take the high ground.'], ['chewie', '(A sage rumble.)']],
          cruiser: [['morty', 'Rick! Rick, it’s the high ground!'], ['rick', 'Don’t, Morty. Don’t try it.']],
          rv: [['jesse', 'He literally just had to not jump, yo.'], ['walt', 'Pride, Jesse. It gets everyone in the end.']],
        },
        pits: [{ at: [0, -74], r: 74, depth: 18, cone: true }],
      },
      {
        id: 'fortress',
        name: 'Fortress Vader',
        at: [-300, -380],
        r: 80,
        about: 'Vader’s castle, built over the lava where he was burned: two black towers, a bacta tank in their foot, and a long bridge out to the landing pad.',
        lines: {
          xwing: [['luke', 'He came back here. To the place where he lost everything.'], ['r2', '(A frightened squeal.)']],
          falcon: [['han', 'Charming. Real homey.'], ['chewie', '(A low, uneasy growl.)']],
          cruiser: [['morty', 'Rick, w-why would you build your house where you got your legs cut off?'], ['rick', 'Feng shui, Morty. Dark side feng shui.']],
          rv: [['walt', 'He built his home on the site of his greatest humiliation.'], ['jesse', 'That’s messed up, Mr. White. Even for you.']],
        },
        things: [
          { kind: 'fortress', at: [0, -18], yaw: 0.67 },
          { kind: 'vadermeditation', at: [8, 34], yaw: 2.6 },
          { kind: 'lamp', at: [-6, 42], opts: { h: 6, light: '#ff6a4a', color: '#1a1a1c' } },
          { kind: 'lamp', at: [18, 44], opts: { h: 6, light: '#ff6a4a', color: '#1a1a1c' } },
        ],
        flat: { r: 50, edge: 20 },
        pits: [
          { at: [-50, 0], r: 26, depth: 14 },
          { at: [52, -6], r: 24, depth: 14 },
        ],
      },
      {
        id: 'falls',
        name: 'The lava falls',
        at: [-252, 74],
        r: 30,
        flat: { r: 14 },
        about: 'Fire pouring off a black butte into a lake of it: the kind of view the Separatists hid behind, and the Mustafarians mine.',
        lines: {
          xwing: [['luke', 'It’s like the whole planet’s bleeding, Artoo.'], ['r2', '(A hushed, awed whistle.)']],
          falcon: [['han', 'Okay. That’s… actually kind of beautiful.'], ['chewie', '(A quiet, impressed rumble.)']],
          cruiser: [['morty', 'Whoa. It’s like a waterfall, but, like, made of death.'], ['rick', 'Basalt magma at twelve hundred degrees, Morty. Nature’s infinity pool.']],
          rv: [['walt', 'Look at that colour. That’s iron, Jesse. And sulphur.'], ['jesse', 'It’s so beautiful it’s kind of messed up, yo.']],
        },
        things: [
          { kind: 'lavafall', at: [-79, 6], yaw: Math.PI / 2, abs: true, y: 32.6, opts: { w: 24, h: 31, bend: 1.4 } },
          { kind: 'lavafall', at: [-94, -30], yaw: 2.2, abs: true, y: 34, opts: { w: 18, h: 32, bend: 1.2 } },
          { kind: 'lavafall', at: [-90, 44], yaw: 0.9, abs: true, y: 34.5, opts: { w: 16, h: 32, bend: 1.2 } },
          { kind: 'smoke', at: [-70, 0], abs: true, y: 4, solid: false, opts: { h: 90, n: 10, color: '#4a3a34', spread: 1.4 } },
        ],
      },
      {
        id: 'camp',
        name: 'The Mustafarian camp',
        at: [150, -250],
        r: 40,
        flat: { r: 28 },
        about: 'Mustafarians in their heat-proof suits, and their lava fleas: they ride them out over the crust to harvest what the lava brings up.',
        lines: {
          xwing: [['luke', 'Lava fleas. Big ones. Don’t get under their back legs, Artoo.']],
          falcon: [['han', 'I’ve seen bigger. Not many.'], ['chewie', '(A doubtful whine.)']],
          cruiser: [['morty', 'Th-those are fleas, Rick? Fleas?!'], ['rick', 'Space fleas, Morty. Everything’s bigger in space.']],
        },
        things: [
          { kind: 'lavaspout', at: [-34, -28], opts: { h: 18, lit: true } },
          { kind: 'crates', at: [8, -6], opts: { color: '#5a4636' } },
          { kind: 'crates', at: [-10, 8], opts: { color: '#5a4636' } },
          { kind: 'fire', at: [0, 2] },
        ],
      },
    ],
    zones: [
      {
        id: 'council',
        name: 'The council room',
        door: { at: [-200, 321.5], r: 3.2, prompt: 'Go into the facility' },
        back: [-200, 326],
        inside: {
          build: 'councilroom',
          spawn: [0, 7.6],
          yaw: Math.PI,
          exit: { at: [0, 9.9], r: 2.2 },
          bounds: [11, 11, 7.4],
          light: { sky: '#7a3a2a', ground: '#ff6a2a', ambient: 0.95, fog: '#1e0e0a', density: 0.02 },
          lamps: [[0, 6.5, 0, '#ffb070', 40, 28], [0, 2.4, 0, '#6ab8ff', 8, 9], [0, 3, -9, '#ff7a3a', 16, 14]],
        },
        life: [
          { kind: 'neimoidian', id: 'gunray', at: [2.2, -5.2], face: 0.3, still: true, name: 'Nute Gunray', says: ['The war is over! Lord Sidious promised us peace. We only want—', 'We have done everything that was asked of us.', 'You— you are not the one we were told to expect.'] },
          { kind: 'geonosian', at: [-2.6, -4.8], face: -0.4, still: true, name: 'Poggle the Lesser', says: ['(A frantic clicking, and his wings buzz.)', '(He points at the hologram, then at the door, then at you.)'] },
          { kind: 'battledroid', n: 2, at: [0, 4], spread: 4, roam: 3, speed: 0.8, name: 'Battle droid', says: ['Roger, roger.', 'The Viceroy is in conference. Uh… he’s busy.'] },
        ],
      },
    ],
    quests: [
      {
        id: 'shutdown',
        name: 'Shut down the droid army',
        about: 'The Separatist council is hiding in the facility. Their droids are still fighting across the galaxy: send the signal that switches them all off.',
        place: 'facility',
        intro: [['C-3PO', 'The Separatist leaders are inside, I believe. If someone were to send the shutdown signal, every battle droid in the galaxy would simply… stop. Imagine!']],
        steps: [
          { type: 'enter', zone: 'council', at: [-200, 317.5], text: 'Get into the council room, through the facility’s door' },
          { type: 'talk', actor: 'gunray', text: 'Find the Viceroy' },
          { type: 'use', zone: 'council', id: 'signal', at: [0, -8.2], r: 2.6, prompt: 'Send the shutdown signal', text: 'Send the shutdown signal from the console', lines: [['Nute Gunray', 'No! The control console— you can’t!']] },
        ],
        done: [['Battle droid', 'Roger, ro…ger……'], ['C-3PO', 'Oh! Every droid in the Separatist army, switched off at once. The war is over!']],
        reward: 'The droid army stands down, all across the galaxy.',
      },
    ],
    things: [
      // the volcanoes, out past the edge
      { kind: 'volcano', at: [1500, 900], model: false, solid: false, opts: { h: 520, r: 760 } },
      { kind: 'volcano', at: [-1300, 1300], model: false, solid: false, opts: { h: 380, r: 600 } },
      { kind: 'volcano', at: [-200, -1700], model: false, solid: false, opts: { h: 600, r: 820 } },
      // geysers along the rivers, platforms adrift
      { kind: 'lavaspout', at: [90, -60], opts: { h: 14 } },
      { kind: 'lavaspout', at: [-120, -200], opts: { h: 20 } },
      // where you set down: the miners' depot on the rock, barrels of what
      // they pull out of the lava
      { kind: 'barrel', at: [104, 12], yaw: 0.3 },
      { kind: 'barrel', at: [105.2, 12.6], yaw: 1.1 },
      { kind: 'barrel', at: [104.4, 13.8], yaw: 2.0 },
      { kind: 'cratecube', at: [108, 10], yaw: 0.6 },
      { kind: 'empirecrate', at: [72, -12], yaw: 1.9 },
      { kind: 'lamp', at: [110, 16], opts: { h: 5, light: '#ffb070', color: '#2a2828' } },
      { kind: 'lamp', at: [68, -16], opts: { h: 5, light: '#ffb070', color: '#2a2828' } },
      { kind: 'lavacollector', at: [182, 34], abs: true, y: 0.25, yaw: 0.7 },
      { kind: 'droidplatform', at: [158, 6], abs: true, y: 1.3 },
      { kind: 'droidplatform', at: [200, 52], abs: true, y: 1.3 },
      { kind: 'droidplatform', at: [290, 322], abs: true, y: 1.3 },
    ],
    scatter: [
      { kind: 'lavacrack', n: 900, within: [10, 585], scale: [1.4, 3.4], solid: false },
      { kind: 'blackspire', n: 90, within: [60, 580], scale: [1.5, 5], opts: { color: '#1c1818' } },
      { kind: 'basalt', n: 90, within: [30, 560], scale: [0.8, 2.2] },
      { kind: 'rock', n: 120, within: [20, 560], scale: [0.6, 2.8], opts: { color: '#2a2422', sharp: 0.7 } },
      { kind: 'stones', n: 240, within: [8, 420], scale: [0.25, 0.8], solid: false, opts: { color: '#2e2624' } },
    ],
    life: [
      { kind: 'obiwan', at: [300, 364], face: 3.14, still: true, blade: { color: '#4a8cff' }, name: 'Obi-Wan Kenobi', says: ['It’s over, Anakin. I have the high ground.', 'Don’t try it.', 'You were the Chosen One! It was said that you would destroy the Sith, not join them!', 'You were my brother, Anakin. I loved you.'] },
      { kind: 'anakin', at: [301, 343.5], face: 0, still: true, blade: { color: '#4a8cff' }, name: 'Anakin Skywalker', says: ['You underestimate my power!', 'If you’re not with me, then you’re my enemy.', 'From my point of view, the Jedi are evil!', 'I hate you!'] },
      { kind: 'vader', at: [-292, -340], face: 0.4, still: true, name: 'Darth Vader', says: ['Be careful not to choke on your aspirations, Director.', 'You were not summoned here to grovel.', '(The breathing. Just the breathing.)', 'I find your lack of faith disturbing.'] },
      { kind: 'mustafarian', n: 2, at: [100, 10], spread: 6, roam: 8, speed: 0.8, name: 'Mustafarian', says: ['(It taps a barrel, then the lava, then the barrel again. The price, presumably.)', '(A hiss through its mask: the heat doesn’t bother it.)'] },
      { kind: 'battledroid', n: 2, at: [74, -8], spread: 6, roam: 8, speed: 1.0, name: 'Battle droid', says: ['Roger, roger.', 'This is a restricted mining zone. Uh… roger?'] },
      { kind: 'mousedroid', n: 1, at: [96, 4], roam: 8, speed: 1.4, r: 0.2, solid: false },
      { kind: 'mustafarian', n: 5, at: [150, -250], spread: 18, roam: 16, speed: 0.9, name: 'Mustafarian', says: ['(It clicks and hisses through its mask, and points at the lava.)', '(It offers you a lump of something still glowing. Cooling, it says. Mostly.)', '(It eyes your boots. They are not rated for this.)'] },
      { kind: 'lavaflea', n: 4, at: [170, -280], spread: 30, roam: 40, speed: 1.6, r: 2.2, name: 'Lava flea', says: ['(It chitters, and a shower of hot grit falls off its shell.)', '(It hops a little closer. Its back legs twitch.)'] },
      { kind: 'battledroid', n: 4, path: [[-232, 330], [-168, 330], [-162, 266], [-238, 266]], speed: 1.2, name: 'Battle droid', says: ['Roger, roger.', 'Halt! This is a restricted facility.', 'The Viceroy is not to be disturbed.', 'Uh oh.'] },
      { kind: 'battledroid', n: 2, at: [-60, 140], spread: 8, roam: 10, speed: 1, name: 'Battle droid', says: ['Landing clearance confirmed. Roger, roger.', 'Is that… a Jedi? Uh oh.'] },
      { kind: 'c3po', at: [-80, 160], roam: 6, speed: 0.6, name: 'C-3PO', says: ['Oh dear. Oh my. I don’t like the look of this at all.', 'Master Anakin? Oh, I do hope he’s all right.', 'This place is far too hot for my circuits.'] },
      { kind: 'droid', at: [-66, 162], roam: 8, speed: 0.6, name: 'R2-D2', says: ['(An urgent string of beeps. Something is very wrong.)', '(A worried whistle, and a look back at the ship.)'] },
    ],
    rides: [{ kind: 'speederbike', at: [-48, 130], yaw: 1.2 }, { kind: 'speederbike', at: [104, -14], yaw: 2.2 }],
    flyovers: [
      { kind: 'shuttle', n: 1, metres: 20, alt: 120, speed: 70, every: 60 },
      { kind: 'vulture', n: 3, metres: 7, alt: 90, speed: 120, every: 70 },
      { kind: 'nubian', n: 1, metres: 29, alt: 70, speed: 80, every: 110 },
    ],
    skyships: [
      { kind: 'destroyer', metres: 1600, at: [-2600, 3400, -6200], yaw: 0.6 },
      // Padmé's skiff, down on the platform
      { kind: 'nubian', metres: 29, at: [-70, 10.5, 150], yaw: 0.3 },
    ],
  },
  scarif: {
    // lit as the game lights its level (src/data/bf2017/light/scarif.json, gameLit.js)
    gameLight: 'scarif',
    place: 'The beaches of Scarif',
    line: 'White sand, palms and turquoise lagoons, under the shield, with the Citadel over all of it.',
    sky: {
      zenith: '#3a86d4',
      horizon: '#c6ecf2',
      haze: 0.7,
      hazeColor: '#e2f6f8',
      suns: [{ az: -0.7, el: 0.62, color: '#fff6e2', size: 0.016, glow: 1.2 }],
      clouds: { cover: 0.28, color: '#ffffff', shade: '#c4d6e2', scale: 0.6, speed: 0.004 },
    },
    fog: { color: '#d0eef2', density: 0.00042 },
    light: { sun: 3.3, sky: '#a8d8f0', ground: '#e0d6b4', ambient: 0.75 },
    dust: '#efe4c8',
    edge: 'Nothing out there but lagoon and sky, and the shield over all of it. Better turn back.',
    ground: { detail: 'beach', detailLook: { color: 0.7, normal: 0.7, metres: 6 },
      seed: 5,
      base: -6,
      wind: 0.6,
      layers: [
        { type: 'island', at: [0, 0], r: 480, height: 9, core: 0.45, ragged: 0.35 },
        { type: 'island', at: [90, 460], r: 230, height: 9, core: 0.5, ragged: 0.25 },
        { type: 'island', at: [-420, 180], r: 190, height: 8, core: 0.4 },
        { type: 'island', at: [380, -330], r: 190, height: 8, core: 0.4 },
        { type: 'swell', scale: 160, height: 1.4 },
        { type: 'dunes', scale: 26, height: 0.6, wind: 0.6 },
      ],
      palette: {
        // (white sand to the trees, the islands' insides scrub and grass)
        low: '#ece6d0',
        high: '#c4c39c',
        rock: '#8e8a78',
        accent: '#7f8f5a',
        deep: '#dccb9e',
        hLow: 1.1,
        hHigh: 4,
        rockAt: 0.4,
        accentCover: 0.38,
        ripple: { strength: 0.05, scale: 2.6, wind: 0.6 },
        grain: 0.45,
        sparkle: 0.04,
        wet: { level: 0, band: 1.3, color: '#b8a682' },
        mark: '#c8b896',
      },
    },
    water: { level: 0, color: '#38c6c8', deep: '#0a5a78', kind: 'sea', foam: 0.55 },
    // (dune grass back from the beaches, sparse, in the sea wind)
    grass: { h: [0.35, 0.8], w: 0.05, root: '#5f7048', mid: '#6f9452', tip: '#adc47e', dry: '#c8c08a', cover: 0.7, scale: 70, above: 1.4, wind: 0.8 },
    weather: [{ kind: 'spray', count: 500 }],
    land: { at: [0, 0], yaw: -0.3 },
    lines: {
      out: {
        xwing: [['luke', 'Scarif. This is where they got the plans, Artoo. All of them, so we could have a chance.'], ['r2', '(A soft, respectful whistle.)']],
        falcon: [['han', 'Nice beach. Shame about the Empire.'], ['chewie', '(A wistful rumble.)']],
        cruiser: [['morty', 'Oh wow, Rick, it’s like a resort! A space resort!'], ['rick', 'It’s a classified Imperial data vault, Morty, with a planetary shield. The worst kind of resort.']],
        rv: [['jesse', 'Yo, Mr. White. Beach. Actual beach.'], ['walt', 'Don’t get comfortable, Jesse. Look at that tower. Nobody builds a tower like that unless they’re hiding something.']],
      },
    },
    places: [
      {
        id: 'pad9',
        name: 'Landing Pad Nine',
        at: [-110, 90],
        r: 30,
        flat: { r: 24 },
        about: 'Where a stolen Imperial cargo shuttle, call sign Rogue One, set down with a rebel crew aboard, cleared through the shield gate by a code that shouldn’t have worked.',
        lines: {
          xwing: [['luke', 'They came in on a stolen shuttle and bluffed their way through the gate.'], ['r2', '(An impressed trill.)']],
          falcon: [['han', 'Stolen shuttle, stolen code, walk right in. Kid after my own heart.']],
          cruiser: [['morty', 'They just… flew in? With a fake code?'], ['rick', 'Imperial cybersecurity, Morty. One password for the whole galaxy.']],
          rv: [['jesse', 'They rolled up in a stolen truck and said they were supposed to be here. Classic.'], ['walt', 'Confidence, Jesse. Nobody questions confidence.']],
        },
        things: [
          { kind: 'pad', at: [0, 0], opts: { r: 18, color: '#a6a49e', light: '#ffd27a', number: 9, shape: 'square' } },
          { kind: 'crates', at: [16, 12], opts: { color: '#8a8a84' } },
          { kind: 'crates', at: [-17, -9], opts: { color: '#8a8a84' } },
          { kind: 'lamp', at: [20, -6], opts: { h: 6, light: '#fff0c8', color: '#5a5c60' } },
          { kind: 'lamp', at: [-20, 8], opts: { h: 6, light: '#fff0c8', color: '#5a5c60' } },
        ],
      },
      {
        id: 'citadel',
        name: 'The Citadel',
        at: [90, 450],
        r: 80,
        flat: { r: 62 },
        about: 'The Empire’s archive: the data vault in its foot, where Jyn and Cassian found the Stardust file, and the great dish on top, that sent the Death Star’s plans out to the fleet.',
        lines: {
          xwing: [['luke', 'The plans came out of there. Off that dish, up to the fleet, and all the way to us.'], ['r2', '(A proud, warbling whistle.)']],
          falcon: [['han', 'That’s one big filing cabinet.'], ['chewie', '(A short laugh.)']],
          cruiser: [['morty', 'Th-they climbed that? The whole thing?'], ['rick', 'Three hundred metres, Morty, in a firefight, to point a dish. Commitment.']],
          rv: [['walt', 'A data vault. Everything they know, in one building, guarded by one door.'], ['jesse', 'That’s, like, the opposite of how you hide stuff.']],
        },
        things: [
          { kind: 'citadel', at: [0, 0], yaw: 2.554 },
          { kind: 'pad', at: [0, 66], opts: { r: 12, color: '#a6a49e', light: '#ffd27a', shape: 'square' } },
          { kind: 'lamp', at: [-14, 58], opts: { h: 7, light: '#fff0c8', color: '#5a5c60' } },
          { kind: 'lamp', at: [14, 58], opts: { h: 7, light: '#fff0c8', color: '#5a5c60' } },
        ],
      },
      {
        id: 'switch',
        name: 'The master switch',
        at: [140, 150],
        r: 22,
        flat: { r: 14 },
        about: 'Out in the open between the pads, the lever that let the transmission through. Chirrut walked to it through the crossfire, blind, saying the words.',
        lines: {
          xwing: [['luke', 'He walked through all that fire to throw a switch. That’s faith, Artoo.'], ['r2', '(A quiet beep.)']],
          falcon: [['han', 'Walked through a firefight, blind, with a stick. Huh.'], ['chewie', '(A respectful growl.)']],
          cruiser: [['morty', '“I’m one with the Force”? And it worked?'], ['rick', 'Statistically it shouldn’t have, Morty. Statistics don’t have a lot of fans in this galaxy.']],
          rv: [['jesse', 'One switch. The whole thing came down to one switch, yo.'], ['walt', 'It usually does.']],
        },
        things: [
          { kind: 'masterswitch', at: [0, 0], yaw: 0.6, scale: 0.5 },
          { kind: 'crates', at: [9, 6], opts: { color: '#8a8a84' } },
        ],
      },
      {
        id: 'beach',
        name: 'The beach',
        at: [-290, -180],
        r: 50,
        about: 'Where the Rebels held the beach among the palms, under the walkers’ guns, long enough for the plans to get out.',
        lines: {
          xwing: [['luke', 'They held this beach against walkers. Against everything.']],
          falcon: [['han', 'AT-ACTs. Cargo walkers. They brought cargo walkers to a beach fight.'], ['chewie', '(A snort.)']],
          cruiser: [['morty', 'Rick! Rick, the giant robot dog is coming!'], ['rick', 'It’s a forklift with legs, Morty. Run anyway.']],
          rv: [['jesse', 'Yo, those things are huge.'], ['walt', 'And slow, Jesse. Keep moving.']],
        },
        things: [
          { kind: 'bunker', at: [30, 26], yaw: -1.2 },
          { kind: 'crates', at: [-8, 18], opts: { color: '#7a7a60' } },
          { kind: 'firefight', at: [10, 0], yaw: 0.6, solid: false, opts: { n: 16, w: 80, d: 60 } },
        ],
      },
      {
        id: 'uwing',
        name: 'The rebel landing',
        at: [-320, 200],
        r: 30,
        flat: { r: 20 },
        about: 'Blue Squadron’s U-wings came in low over the palms and dropped the Pathfinders into the jungle to start the fight on the beach.',
        lines: {
          xwing: [['luke', 'U-wings. They dropped the troops in right here.'], ['r2', '(A busy series of beeps.)']],
          falcon: [['han', 'Nice drop zone. Lots of cover. Lots of sand in your boots.']],
          cruiser: [['morty', 'Rick, there’s a whole rebel army in the trees!'], ['rick', 'Pathfinders, Morty. Space marines with better branding.']],
        },
        things: [
          { kind: 'crates', at: [10, -8], opts: { color: '#6a6a4a' } },
          { kind: 'crates', at: [-9, 10], opts: { color: '#6a6a4a' } },
          { kind: 'fire', at: [-4, -6] },
        ],
      },
      {
        id: 'lastbeach',
        name: 'The last sunset',
        at: [430, -250],
        r: 30,
        about: 'Where Jyn and Cassian made it to the water’s edge, and held on to each other, and watched the light come over the sea.',
        lines: {
          xwing: [['luke', 'They got the plans out, and then they came here. They knew.'], ['r2', '(A very long, very quiet whistle.)']],
          falcon: [['han', '…Yeah. Let’s give ’em a minute.'], ['chewie', '(A soft, low moan.)']],
          cruiser: [['morty', 'Rick, that’s— is that the Death Star? Over the water?'], ['rick', '…Yeah, Morty. Yeah, it is. Let’s… let’s not stay for this one.']],
          rv: [['jesse', 'They knew it was coming, man. They just… sat on the beach.'], ['walt', 'They finished the job, Jesse. That’s what you do.']],
        },
      },
    ],
    zones: [
      {
        id: 'vault',
        name: 'The data vault',
        door: { at: [79.3, 396.6], r: 3.5, prompt: 'Go into the data vault' },
        back: [78.6, 392.6],
        inside: {
          build: 'datavault',
          spawn: [0, 21.5],
          yaw: Math.PI,
          exit: { at: [0, 24.6], r: 2.2 },
          bounds: [8, 26, 14],
          light: { sky: '#4a6a9a', ground: '#1a2a3a', ambient: 0.85, fog: '#0a121c', density: 0.012 },
          lamps: [[0, 12, 0, '#a8d0ff', 30, 40], [0, 8, -18, '#8ab8ff', 20, 24], [0, 8, 16, '#8ab8ff', 16, 24]],
        },
        life: [
          { kind: 'krennic', at: [0, -12], face: 0, still: true, name: 'Director Krennic', says: ['Who are you?', 'We were on the verge of greatness. We were this close to providing peace and security for the galaxy.', 'Your father’s revenge. He built a flaw in it, and he’s ruined everything.'] },
          { kind: 'deathtrooper', n: 2, path: [[-2.4, -9], [2.4, -9]], still: true, face: 0, name: 'Death trooper', says: ['(A burst of distorted, unintelligible comms chatter.)'] },
        ],
      },
    ],
    quests: [
      {
        id: 'plans',
        name: 'The Stardust file',
        about: 'The Death Star’s plans are in the Citadel’s vault, filed under Stardust. Get them out, and get the switch thrown so the transmission can go up to the fleet.',
        intro: [['K-2SO', 'The plans are in the data vault under the Citadel. The file is called Stardust. Please try not to get shot. I calculate you will get shot.']],
        steps: [
          { type: 'enter', zone: 'vault', at: [79.3, 396.6], text: 'Get into the data vault, at the foot of the Citadel' },
          { type: 'use', zone: 'vault', id: 'stardust', at: [0, -21.4], r: 2.6, prompt: 'Pull the Stardust file', text: 'Find the Stardust file, at the end of the vault', lines: [['Director Krennic', 'Who are you?']] },
          { type: 'reach', at: [140, 150], r: 9, text: 'Get to the master switch', lines: [['K-2SO', 'Bodhi says the shield gate is closed. Somebody has to throw the master switch, out in the open. It will not be me.']] },
          { type: 'use', id: 'switch', at: [140, 150], r: 4, prompt: 'Throw the master switch', text: 'Throw the master switch' },
        ],
        done: [['Chirrut Îmwe', 'I am one with the Force, and the Force is with me.'], ['K-2SO', 'The transmission is through. The fleet has the plans. That was… acceptable.']],
        reward: 'The plans are away, up to the fleet. Rebellions are built on hope.',
      },
    ],
    things: [
      // the shield overhead, and the Death Star over the eastern sea
      { kind: 'scarifshield', at: [0, 0], abs: true, y: -400, model: false, solid: false },
      // (the universe's own Death Star model, over the eastern sea, clear of the fog; the built sphere if it won't load)
      { kind: 'ds1sky', url: '/models/universe/death-star.glb', metres: 3000, centred: true, at: [8800, -1900], abs: true, y: 1250, yaw: -1.35, model: false, solid: false, fog: false, opts: { r: 1500 } },
      // the Empire's cargo where you land, waiting for the next shuttle
      { kind: 'empirecrate', at: [22, -18], yaw: 0.3 },
      { kind: 'empirecrate', at: [22.4, -16.6], yaw: 0.2 },
      { kind: 'cratecube', at: [25, -19], yaw: 1.1 },
      { kind: 'cratecube', at: [26.3, -18.4], yaw: 0.4 },
      { kind: 'cratecube', at: [-20, 14], yaw: 2.2 },
      { kind: 'cooler', at: [-18, 16], yaw: 0.6 },
      { kind: 'barrel', at: [24, -14], yaw: 0.9 },
      // pads, bunkers and lamps across the base
      { kind: 'pad', at: [60, 60], opts: { r: 16, color: '#a6a49e', light: '#ffd27a', shape: 'square' } },
      { kind: 'pad', at: [210, 40], opts: { r: 16, color: '#a6a49e', light: '#ffd27a', shape: 'square' } },
      { kind: 'pad', at: [40, 210], opts: { r: 14, color: '#a6a49e', light: '#ffd27a', shape: 'square' } },
      { kind: 'pad', at: [-60, -110], opts: { r: 16, color: '#a6a49e', light: '#ffd27a', shape: 'square' } },
      { kind: 'pad', at: [120, -120], opts: { r: 14, color: '#a6a49e', light: '#ffd27a', shape: 'square' } },
      { kind: 'bunker', at: [100, 100], yaw: 2.3 },
      { kind: 'bunker', at: [-30, 150], yaw: 3.0, scale: 1.4, opts: { w: 18, d: 12 } },
      { kind: 'bunker', at: [200, 120], yaw: 1.8 },
      { kind: 'bunker', at: [-150, -40], yaw: -1.4 },
      { kind: 'bunker', at: [40, -170], yaw: 0.2, scale: 1.6, opts: { w: 20, d: 12 } },
      { kind: 'bunker', at: [150, 300], yaw: 3.4 },
      { kind: 'lamp', at: [30, 24], opts: { h: 6, light: '#fff0c8', color: '#5a5c60' } },
      { kind: 'lamp', at: [-24, 34], opts: { h: 6, light: '#fff0c8', color: '#5a5c60' } },
      { kind: 'lamp', at: [80, 180], opts: { h: 6, light: '#fff0c8', color: '#5a5c60' } },
      { kind: 'lamp', at: [170, 80], opts: { h: 6, light: '#fff0c8', color: '#5a5c60' } },
    ],
    scatter: [
      { kind: 'palm', n: 600, within: [34, 585], scale: [0.7, 1.3], above: 0.7, clear: 6 },
      // (the scrub back from the beaches, low and round, under the palms; thicker in the islands' hearts)
      { kind: 'bush', n: 700, within: [20, 570], scale: [0.7, 1.7], solid: false, above: 1.0, opts: { seed: 12, s: 2.2, color: '#4a5e3a' } },
      { kind: 'bush', n: 260, within: [20, 300], scale: [0.5, 1.1], solid: false, above: 1.4, opts: { seed: 15, s: 1.6, color: '#587a3c' } },
      { kind: 'rock', n: 70, within: [60, 560], scale: [0.6, 2.2], opts: { color: '#9a9484', sharp: 0.3 } },
      { kind: 'stones', n: 220, within: [8, 500], scale: [0.2, 0.5], solid: false, opts: { color: '#b8b098' } },
      // the undergrowth under the palms, ferns and broad leaves
      { kind: 'sorganfern', n: 340, within: [20, 560], scale: [1, 2.2], solid: false, above: 1.2 },
    ],
    life: [
      // (the Empire's walkers on the beach: the rigged AT-AT model, walking its own walk; the film's cargo walkers are its taller cousins)
      { kind: 'atat', n: 1, path: [[-250, -60], [-330, -260], [-180, -330], [-120, -200]], speed: 2.4, r: 4.5, scale: 1, name: 'Imperial walker', says: ['(The walker’s head swings your way, and its chin guns with it.)'] },
      { kind: 'atat', n: 1, path: [[-120, -200], [-250, -60], [-330, -260], [-180, -330]], speed: 2.4, r: 4.5, scale: 1, name: 'Imperial walker', says: ['(It stalks on down the beach, the sand shaking under each foot.)'] },
      { kind: 'shoretrooper', n: 4, path: [[-90, 70], [-130, 70], [-130, 110], [-90, 110]], speed: 1.4, name: 'Shoretrooper', says: ['Halt. This pad is restricted.', 'Your shuttle’s clearance code is… in order. Proceed.', 'Rebels on the beach! Get to the walkers!', 'Keep your eyes on the tree line.'] },
      { kind: 'shoretrooper', n: 3, at: [140, 150], spread: 16, roam: 18, speed: 1.2, name: 'Shoretrooper', says: ['Stay away from the switch!', 'Who’s that? The blind one? Shoot him!', 'Squad, form up on the pad!'] },
      { kind: 'deathtrooper', n: 2, at: [90, 520], spread: 6, roam: 6, speed: 1, name: 'Death trooper', says: ['(A burst of distorted, unintelligible comms chatter.)', '(It turns its head to follow you. It says nothing at all.)'] },
      { kind: 'stormtrooper', n: 3, at: [70, 515], spread: 12, roam: 14, speed: 1.1, name: 'Stormtrooper', says: ['Access to the vault is restricted.', 'Director Krennic is on his way down.', 'Seal the tower!'] },
      { kind: 'rebel', n: 6, at: [-320, 200], spread: 18, roam: 22, speed: 1.4, name: 'Pathfinder', says: ['Rogue One, we’re with you!', 'Find cover! Walkers on the beach!', 'Blue Squadron, we need that gate kept open!', 'For the Rebellion!'] },
      { kind: 'rebel', n: 3, at: [-280, -170], spread: 14, roam: 12, speed: 1.3, name: 'Rebel trooper', says: ['Keep their heads down! Give Rogue One time!', 'Here comes another walker!'] },
      // (Sefla's Pathfinders on the beach, and Bodhi at the shuttle, the quests of the fight)
      { kind: 'rebel', id: 'sefla', at: [-296, -172], still: true, face: 0.6, name: 'Lieutenant Sefla', named: true, quest: 'walkers', says: ['Those walkers will roll right over us unless somebody gets under them.'] },
      { kind: 'rebelpilot', id: 'bodhi', at: [-98, 82], roam: 5, speed: 0.9, name: 'Bodhi Rook', named: true, quest: 'rogueone', says: ['I’m the pilot. I’m the pilot!', 'The shield gate’s closed. We have to tell the fleet.', 'This is Rogue One. Rogue One, calling any Alliance ships.'] },
      { kind: 'shoretrooper', n: 2, at: [20, -10], spread: 4, still: true, face: 2.8, name: 'Shoretrooper', says: ['Cargo manifest, pilot.', 'Nobody touches the crates till the shuttle’s down.'] },
      { kind: 'mousedroid', n: 2, at: [0, 8], spread: 8, roam: 14, speed: 1.6, r: 0.2, solid: false },
      { kind: 'baze', at: [-92, 110], roam: 6, speed: 0.7, name: 'Baze Malbus', says: ['Good luck.', 'I don’t need luck. I have you.', '(He checks the cannon’s power pack. Again.)'] },
      { kind: 'k2so', id: 'k2so', quest: 'plans', at: [-96, 104], roam: 8, speed: 1.0, name: 'K-2SO', says: ['Congratulations. You are being rescued. Please do not resist.', 'I have a bad feeling about— no. Actually, I do not.', 'The captain says you are a friend. I will not kill you.', 'There is a ninety-seven point six percent chance of failure. Shall we proceed?', 'Jyn, I’ll be there for you. Cassian said I had to.'] },
      { kind: 'chirrut', at: [128, 140], roam: 8, speed: 0.6, name: 'Chirrut Îmwe', says: ['I am one with the Force, and the Force is with me.', 'The strongest stars have hearts of kyber.', 'Look for the Force, and you’ll always find me.', 'You might as well be blind.'] },
      { kind: 'jyn', at: [438, -246], face: 1.6, still: true, name: 'Jyn Erso', says: ['Rebellions are built on hope.', 'Save the Rebellion. Save the dream.', 'Your father would be proud of you, Cassian.'] },
      { kind: 'cassian', at: [436, -252], face: 1.6, still: true, name: 'Cassian Andor', says: ['Your father would be proud of you, Jyn.', 'I’ve been in this fight since I was six years old.', 'Welcome home, Jyn.'] },
    ],
    rides: [{ kind: 'speederbike', at: [36, -30], yaw: 2.6 }],
    flyovers: [
      { kind: 'xwing', n: 2, metres: 12.5, alt: 80, speed: 110, every: 45 },
      { kind: 'uwing', n: 1, metres: 24, alt: 60, speed: 80, every: 70 },
      { kind: 'tie', n: 2, metres: 7, alt: 90, speed: 130, every: 50 },
      { kind: 'ywing', n: 2, metres: 16, alt: 100, speed: 90, every: 80 },
    ],
    skyships: [
      // the shield gate overhead, and its guard
      { kind: 'gate', metres: 2600, at: [-3000, 3300, 6400], yaw: 0.4 },
      { kind: 'destroyer', metres: 1600, at: [-1200, 2900, 6600], yaw: 2.6 },
      { kind: 'destroyer', metres: 1600, at: [-4800, 3400, 4600], yaw: 1.9 },
      // Rogue One on its pad, and a U-wing on the landing ground
      { kind: 'shuttle', metres: 20, at: [-110, 7.5, 90], yaw: 0.8 },
      { kind: 'uwing', metres: 24, at: [-320, 8.5, 200], yaw: -0.6 },
    ],
  },
};
